version: 2.1
orbs:
  node: circleci/node@3.0.0
  coveralls: coveralls/coveralls@1.0.6
  alexjs-orb: lauravuo/alexjs-orb@0.0.1
jobs:
  coverage:
    docker:
      - image: 'circleci/node:10.0.0'
    steps:
      - checkout
      - run:
          name: Install and Test
          command: npm install && npm run coverage
      - coveralls/upload:
          parallel: true
          verbose: true
workflows:
  node-tests:
    jobs:
      - node/tests:
          matrix:
            parameters:
              version:
                - 16
                - 14
                - 12
                - 10
      - alexjs-orb/lint
      - coverage

